version: '3.8'

services:
  app:
    image: berlin16/blog-platform:latest
    container_name: blog-platform
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DSN=root:GB_UXa>cX*h!K2@tcp(db:3306)/blog_db?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - db
    networks:
      - blog-net

  db:
    image: mysql:8.0
    container_name: blog-stats-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: GB_UXa>cX*h!K2 
      MYSQL_DATABASE: blog_db
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - blog-net

networks:
  blog-net:
    driver: bridge